### ISSUE TITLE
Metric for validation?

### ISSUE THREAD

**Issue by ZhiliWang** [smacawi/bert-topics#1]
Hi. This is an awesome project and I am also working on using transformer model embeddings for topic modeling. I am wondering if there can possibly be a good metric to validate the models. I use perplexity for LDA but not sure if it's suitable with BERTs (and other transformers models). Thank you!

**Comment by mirandrom** [comment]
Hi Zhili, apologies for the delayed reply. We will be publishing our paper soon, and share it with you. 

For the time being, here is the relevant excerpt from the paper:

> C_V was found by [Röder et al. (2015)](https://doi.org/10.1145/2684822.2685324) to be the most interpretable topic coherence metric when compared to human judgement and has later been used  extensively  on  assessing  the  coherence  of short texts like tweets as well ([Zeng et al., 2018](https://doi.org/10.18653/v1/D18-1351); [Habibabadi  and  Haghighi,  2019](https://doi.org/10.1145/3290688.3290735);  [Wallner  et  al.,2019](https://doi.org/10.1109/CIG.2019.8848079)). We also use C_NPMI, which has been one of the most successful topic coherence measures based on direct confirmation ([Röder et al., 2015](https://doi.org/10.1145/2684822.2685324); [Lau et al., 2014](https://doi.org/10.3115/v1/E14-1056)).

In particular, we use tf-idf and an attention-weighted version of tf-idf to extract keywords, allowing us to use these coherence metrics. Because these metrics are still limited, we also implemented human evaluation. In our approach, we asked evaluators to rate clusters of tweets and their keywords on informativeness and usefulness, as well as identify intruders in the clusters.
